#!/bin/sh

/usr/lib/geoclue-2.0/demos/agent &

gammastep -c ~/.config/config.ini &

swaybg -i ~/Immagini/archlinux.jpg &

#while true; do
#yambar
#done

someblocks -p | dwlb -status-stdin all &

dwlb &
 
