#!/bin/sh

nm-applet &

if xrandr | grep "HDMI1 connected"; then
	xrandr --output HDMI1 --auto --left-of LVDS1
fi

/usr/lib/geoclue-2.0/demos/agent &

redshift-gtk &

picom -f &

feh --bg-fill /home/rene/Images/archlinux6.jpg & 

while true
do
        vol=$(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')
        time=$(date +"%R | %A %d/%B/%Y")
        temp="$(($(cat /sys/class/thermal/thermal_zone0/temp) / 1000))C"
        bat=$(acpi | awk '{print $4}' | tr -d ",")

        xsetroot -name "🔋$bat $temp 🔉$vol $time"
        
        sleep 1m
done &

#while true; do
#	dwm >/dev/null 2>&1
#done 

exec dwm
